export const authConstants={
    LOGIN_REQUEST:'LOGIN_REQUEST',
    LOGIN_FAILED:'LOGIN_FAILED',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGOUT_REQUEST:'LOGOUT_REQUEST',
    LOGOUT_SUCCESS:'LOGOUT_SUCCESS',
    LOGOUT_FAILED:'LOGOUT_FAILED'
}

export const userConstants={
    USER_REGISTER_REQUEST:'USER_REGISTER_REQUEST',
    USER_REGISTER_SUCCESS:'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAILED:'USER_REGISTER_FAILED'
}